2024-11-03 17:07:25,946 - app.router.User.register - INFO - Attempting to register user with email: user@example1.com
2024-11-03 17:07:25,971 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/cuong/Desktop/best_code/F5/backend/env/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-03 17:07:26,341 - app.router.User.register - INFO - User registered successfully with email: user@example1.com, ID: 1
2024-11-03 17:07:29,200 - app.router.User.register - INFO - Attempting to register user with email: user@example1.com
2024-11-03 17:07:29,214 - app.router.User.register - WARNING - Registration failed: Email user@example1.com is already registered.
2024-11-03 17:08:13,444 - app.router.User.register - INFO - Attempting to register user with email: user1@example.com
2024-11-03 17:08:13,790 - app.router.User.register - INFO - User registered successfully with email: user1@example.com, ID: 2
2024-11-03 17:09:10,385 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:10,749 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:12,051 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:12,391 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:14,472 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:14,787 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:17,032 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:17,346 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:27,090 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:27,410 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:32,643 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:32,961 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:09:34,317 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:09:34,635 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:13:29,527 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:13:29,910 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:27:56,573 - app.router.User.register - INFO - Attempting to register user with email: cuong@gmail.com
2024-11-03 17:27:57,051 - app.router.User.register - INFO - User registered successfully with email: cuong@gmail.com, ID: 3
2024-11-03 17:29:29,562 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:29:29,948 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 17:29:47,131 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 17:29:47,485 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-03 18:29:17,806 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:20,676 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:21,157 - app.router.User.auth - WARNING - Login failed for username: user1@example.com - Incorrect password
2024-11-03 18:29:30,855 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:31,178 - app.router.User.auth - WARNING - Login failed for username: user1@example.com - Incorrect password
2024-11-03 18:29:33,215 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:33,534 - app.router.User.auth - WARNING - Login failed for username: user1@example.com - Incorrect password
2024-11-03 18:29:34,062 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:34,247 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:34,407 - app.router.User.auth - WARNING - Login failed for username: user1@example.com - Incorrect password
2024-11-03 18:29:34,722 - app.router.User.auth - WARNING - Login failed for username: user1@example.com - Incorrect password
2024-11-03 18:29:50,926 - app.router.User.auth - INFO - Received login attempt for username: user1@example.com
2024-11-03 18:29:51,289 - app.router.User.auth - INFO - Login successful for username: user1@example.com
2024-11-04 12:58:05,105 - app.router.User.register - INFO - Attempting to register user with email: admin@example.com
2024-11-04 12:58:05,167 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/cuong/Desktop/best_code/F5/backend/env/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-04 12:58:05,567 - app.router.User.register - INFO - User registered successfully with email: admin@example.com, ID: 4
2024-11-04 12:58:56,906 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-04 12:58:57,276 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-04 15:28:55,284 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-04 15:28:55,524 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-04 15:28:55,750 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-04 23:21:19,995 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-04 23:21:20,028 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-04 23:21:20,448 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-05 13:01:26,614 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-05 13:01:26,683 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-05 13:01:26,916 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-05 21:39:34,643 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-05 21:39:34,660 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-05 21:39:35,123 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-06 09:55:02,855 - app.router.User.auth - INFO - Received login attempt for username: admin@example
2024-11-06 09:55:02,932 - app.router.User.auth - WARNING - Login failed for username: admin@example - User not found
2024-11-06 09:55:09,956 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-06 09:55:10,513 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-06 09:55:10,740 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-06 14:49:39,264 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-06 14:49:39,324 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-06 14:49:39,793 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-06 18:50:23,961 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-06 18:50:24,016 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-06 18:50:24,246 - app.router.User.auth - INFO - Login successful for username: admin@example.com
2024-11-07 00:42:32,558 - app.router.User.auth - INFO - Received login attempt for username: admin@example.com
2024-11-07 00:42:32,586 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/biennguyen0304/btecthi/bteccoder/F5/backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-11-07 00:42:32,812 - app.router.User.auth - INFO - Login successful for username: admin@example.com
